### ISSUE TITLE
Update requirements file

### ISSUE THREAD

**Issue by nsryan2** [arfc/pygenesys#22]
Installing with the `pip install -e .` option, and then running the `genesys --infile examples/example_inputfile.py` input example required me to install xlrd and openpyxl before it could read the inputs.

To replicate, though this was probably unique to my conda environment, follow the readme instructions for pygenesys and temoa, and run the example input from above.

**Comment by samgdotson** [comment]
I've encountered this a couple of times, now. Apparently using `pandas.read_excel` defaults to using `openpyxl`, but pandas doesn't require `openpyxl` as a dependency. This is fixed in PR #43!

**Comment by nsryan2** [comment]
Closing as it seems to have been addressed in #43
