### ISSUE TITLE
Basic Installation method doesn't add pygenesys to the path

### ISSUE THREAD

**Issue by nsryan2** [arfc/pygenesys#24]
As mentioned in #21 the method `pip install .` doesn't seem to add pygenesys to the users PYTHONPATH, whereas the `pip install -e .` method does. As a result, installs with this basic method will not work as is.

**Comment by samgdotson** [comment]
There is likely more troubleshooting needed. I'm not 100% sure it's a PATH issue, but it could be.

**Comment by nsryan2** [comment]
To my understanding, this issue was resolved in some in-person discussion.
