### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by yardasol** [arfc/pygenesys#40]
The main `README` file in the repo references an installation option for people who want to contribute to PyGenESys. Consider adding contribution guidelines or a reference/link to contribution guidelines.

This PR can be closed when a PR exists that adds either a file with contribution guidelines to the repo and points to said file in the `README`, or a link in the `README` to some externally located contribution guidelines.

**Comment by munkm** [comment]
Related: arfc/pygenesys#25

**Comment by samgdotson** [comment]
I'm closing this issue since it is a duplicate of #25
